//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewPictures {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class stringLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal stringLanguage() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViewPictures.stringLanguage", typeof(stringLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разрешенные операции над файлом.
        /// </summary>
        internal static string InformationAllowedFileOperations {
            get {
                return ResourceManager.GetString("InformationAllowedFileOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время создания в UTC.
        /// </summary>
        internal static string InformationCreationTimeInUTC {
            get {
                return ResourceManager.GetString("InformationCreationTimeInUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата создания.
        /// </summary>
        internal static string InformationDateOfCreation {
            get {
                return ResourceManager.GetString("InformationDateOfCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Атрибуты файла.
        /// </summary>
        internal static string InformationFileAttributes {
            get {
                return ResourceManager.GetString("InformationFileAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расширение файла.
        /// </summary>
        internal static string InformationFileExtension {
            get {
                return ResourceManager.GetString("InformationFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группа файла.
        /// </summary>
        internal static string InformationFileGroup {
            get {
                return ResourceManager.GetString("InformationFileGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя файла.
        /// </summary>
        internal static string InformationFileName {
            get {
                return ResourceManager.GetString("InformationFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Владелец файла.
        /// </summary>
        internal static string InformationFileOwner {
            get {
                return ResourceManager.GetString("InformationFileOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер файла.
        /// </summary>
        internal static string InformationFileSize {
            get {
                return ResourceManager.GetString("InformationFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип файла.
        /// </summary>
        internal static string InformationFileType {
            get {
                return ResourceManager.GetString("InformationFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полный путь.
        /// </summary>
        internal static string InformationFullPath {
            get {
                return ResourceManager.GetString("InformationFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата последнего доступа.
        /// </summary>
        internal static string InformationLastAccessDate {
            get {
                return ResourceManager.GetString("InformationLastAccessDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время последнего доступа в UTC.
        /// </summary>
        internal static string InformationLastAccessTimeInUTC {
            get {
                return ResourceManager.GetString("InformationLastAccessTimeInUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата последнего изменения.
        /// </summary>
        internal static string InformationLastModifiedDate {
            get {
                return ResourceManager.GetString("InformationLastModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время последнего изменения в UTC.
        /// </summary>
        internal static string InformationLastModifiedTimeInUTC {
            get {
                return ResourceManager.GetString("InformationLastModifiedTimeInUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Родительская папка.
        /// </summary>
        internal static string InformationParentFolder {
            get {
                return ResourceManager.GetString("InformationParentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер.
        /// </summary>
        internal static string InformationSizePhoto {
            get {
                return ResourceManager.GetString("InformationSizePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Масштаб.
        /// </summary>
        internal static string photoScale {
            get {
                return ResourceManager.GetString("photoScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер фото.
        /// </summary>
        internal static string photoSize {
            get {
                return ResourceManager.GetString("photoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на байт.
        /// </summary>
        internal static string textByte {
            get {
                return ResourceManager.GetString("textByte", resourceCulture);
            }
        }
    }
}
